spring:
  application:
    name: judgeoverflow
  # Security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(a1ZwUcY0/bhNoUXklI+AAN5S6UH9Ou6C5BwIHMUa7kBiCaeiPBug5aDAdhDmLfsCKFYc+TQRdXUiyz1OERxgl3PIq66At8BYa4sPpUFnt9jSmBaObWPa+8SLJvpeDlMbkEgqXJhJ5WlkQbCBLycfLw==)
            client-secret: ENC(pvII7YF9JYTHc/CwFhyOBfgCm60R3hjSMEl26Y1K6r7lg/LRwBeUQKHMQpvH8xBgojbaOTnfzsBkk/IssI33qMBvjYU1arac9dA0G14v80M=)
          github:
            client-id: ENC(+uvt50eXMLftMwES9Z8iRxmJoA1hquNZpJEHwkusaiEyEoDgcdrec/w6/JOb9bExBN0eonGHcvA3N+HdWet7zQ==)
            client-secret: ENC(9EYDzWTL+RG+XgfTIjZwZQgu7q6MoENNPBezk6SJlEr5wiJKZW77Scbr6FVRDZds9AJOzNpi5fCe5SuYkncg2QwCjMbaVPewR8nUWpaCxpQ=)
            scope:
              - user:email
  # DB
  datasource:
    url: jdbc:postgresql://localhost:5432/judgeoverflow
    username: ENC(zi2rzPiqq7WKfbVD4rhFbIzFx8SqMHMiTXUpZQjhXVveY/2xjm05LJxnM+GEVrSP)
    password: ENC(J8GMrasqQQ1hYC0fSJmMS65nVa6LcEwmMTb/p+Jtc6r0z4NkDCvv7nZ9XmOYRzcJ8fF2EtDFQfxNIyzEvZQStA==)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

#logging:
#  level:
#    org.springframework.security: DEBUG